import { assignStaffToContractTemplate, createContractTemplate, getAllContractTemplate, getAllContractTemplatesForOrganization, getContractTemplateVersion } from "./module/contract-template";
import { createDesignation, designateStaff, getAllDesignation, getAllTeamDesignation, getAllTeamDesignationsByOrganizationId, 
  updateDesignation, updateTeamDesignation } from "./module/designation";
import { approveMultiplePayrolls, approvePayroll, assignStaffToPayrollTemplate, createPayroll, createPayrollTemplate, createSinglePayroll, 
  disapproveMultiplePayrolls, 
  disapprovePayroll, generatePayroll, getAllPayrollsForOrganization, getAllPayrollsGroupedByMonth, getAllPayrollTemplatesForOrganization, 
  getApprovedPayrollsByTemplateAndMonth, getEmployeePayrollByStaffId, getPayrollsByTemplateAndMonth, getPayrollsGroupedByMonthForStaff,
   getPayrollTemplateById, getPreviousMonthPayrolls, getUnapprovedPayrollsByTemplateAndMonth, getUserPayrollByTemplateAndMonth, updatePayroll, updatePayrollTemplate } from "./module/payroll";
import {
  createStaff, getAllStaffs, getAllStaffsWithoutRoles, getSingleStaffById, getStaffById, getStaffByUserId, getStaffsByOrganizationId,
  getStaffWithContractTemplate, getStaffWithPayrollTemplate, updateStaff, createExternalStaffBulkUpload,
  createStaffBulkUpload, updateStaffDepartment,
  makeStaffHead,
  makeStaffHeadOfDepartment,
  getStaffProfileByUserId,
  getStaffByOrganizationId,
} from "./module/staff";
import { createStaffRole, getAllStaffRole } from "./module/staff-role";
import { createTeam, getAllParentTeams, getAllTeamMember, getAllTeams, getSingleTeamById, getTeamDesignationsByTeamId, 
  getTeamsByOrganizationId, getUniqueTeamsFromTeamDesignationsByOrganizationId, 
getAllParentTeamByOrganizations,
updateTeam,
getAllParentTeamByOrganizationId,
 } from "./module/team";
import {
  createUser,
  getAllUsers,
  getRoles,
  getSingleUserById,
  getUserById,
  getUserRoles,
  getUsersByOrganizationId,
  updateUserRole,
  getUsersForTaskByOrganizationId,
} from "./module/user";
import { deleteNotification, markNotificationAsRead, getAllNotificationByUserId, getNotificationById, getUnreadNotificationCount } from "./module/notification";
import { createLeaveSetting, getAllLeaveSetting, updateLeaveSetting, deleteLeaveSetting, getLeaveSettingByOrganizationId } from "./module/leave";
import { createWorkHistory, getAllWorkHistory } from "./module/work-history";
import {
  createLeaveApplication, getAllLeaveApplication, updateLeaveApplication,
  deleteLeaveApplication, getAllPendingLeaveApplicationByOrganization,
  getAllLeaveApplicationByOrganization, getAllApprovedLeaveApplicationByOrganization, 
  getAllRejectedLeaveApplicationByOrganization, getLeaveApplicationById, changeLeaveApplicationStatus,
  attendToLeaveApplication
} from "./module/leave";
import {
  createLoanSetting, deleteLoanSetting, updateLoanSetting, getLoanSettingById,
  getAllLoanSettingByOrganizationSlug, applyForLoan,
  getLoanSettingByOrganizationSlug, updateLoanApplication, deleteLoanApplication,
  getAllLoanApplicationByUserId, getAllLoanApplicationByOrganizationSlug, changeLoanApplicationStatus,
  getAllPendingLoanApplicationByOrganizationSlug, getAllApprovedLoanApplicationByOrganizationSlug, getAllRejectedLoanApplicationByOrganizationSlug,
  getLoanApplicationById,
  disburseLoan,
  attendToLoanManagement
} from "./module/loan";
import { publicProcedure, router } from "./trpc";
import { createEvent, deleteEvent, getAllBirthdayEventsForOrganizationBySlug, getAllEventOfAnOrganization, getAllEventsForCalenderByOrgSlug, 
  getAllEventsForOrganizationBySlug, getAllEventsGroupedByMonth, getEvents, getEventsByDateRange, updateEvent } from "./module/event";
import {
  createBroadcast, createChat, createComplaint, createFeedback, getActiveUsers, getChatMessages, getComplaintChats, getDraftChatById, getDraftCount,
  getDraftMessages, getFeedbackChats, getGroupChatMessages, getGroupChats, 
  getParentComplaintAndFeedbackMessages, getRecipients, getSentMessages, getTrashedMessages,
   getUnreadMessageCount, getUserChats, markComplaintAsClosed, markFeedbackAsResolved, markMessagesAsRead, 
   saveBroadcastDraft, sendDraft, sendMessage, updateDraft
} from "./module/communication";
import {
  createPerformanceReviewTemplate, createPerformanceForStaffReview,
  getAllAssignedPerformanceReviewTemplateToTeam, deletePerformanceReviewTemplate,
  getAllPerformanceReviewTemplateByOrganizationSlug, updatePerformanceReviewTemplate,
  deletePerformanceReview, updatePerformanceReview, getAllPerformanceReviewByOrganizationSlug,
  assignPerformanceReviewTemplateToTeam, getPerformanceReviewAssignedById, findPerformanceReviewByStaffId,
  getAllUnassignedPerformanceReviewByOrganizationSlug,
  findPerformanceReviewById,
  getAllStaffForReviewByOrgIdAndRange,
  getPerformanceReviewTemplateAssignmentId,
  getAllUnassignedPerformanceReviewByOrganizationSlugAndRoleLevel,
  getPerformanceReviewRoleLevelRangeById,
  getPerformanceReviewRoleLevelAndId,
  getAllUnassignedPerformanceReviewByOrganizationSlugAndRoleLevelOnly,
  getAllTeamPerformanceReviewsByOrg,
} from "./module/performance-review";
import { createLoanRepayment, getAllLoanRepayment, getGroupedLoanRepayments } from "./module/loan-repayment";
import { createOrganization, getActiveOrganization, getAllOrganization } from "./module/organization";
import { createAdmin, getAllAdmins } from "./module/admins";
import { generateUserToken, verifyToken } from "./module/generate-token";
import { approvePolicyAndProcedure, createPolicyAndProcedure, deletePolicyAndProcedure, 
  getAllPolicyAndProcedureByOrganization, getPolicyAndProcedureById, updatePolicyAndProcedure } from "./module/policy-procedures";

  import { updateContractTemplate, deleteContractTemplate } from "./module/contract-template";
import { createBank, editBankTable, getAllBanks, getAllBanksByOrganizationId } from "./module/bank";
import { documentsPreference, findDocumentPreferenceByOrganizationSlug, findHomeLinkPreferenceByOrganizationSlug, findOrganizationLogoPreferenceByOrganizationSlug, getOrganizationPreference, homeLinkPreference, organizationLogoPreference } from "./module/preference";
import { getAllTasksByOrganization, getTaskById, createTask, staffGetTaskById , staffSubmitTask, getStaffTasksByUser, getStaffTaskById} from "./module/task";
import { createIncome, getAllIncomeAccounts } from "./module/income";
import { createAccount, createBill, createInvoice, createPayment, downloadAccountStatement, getAccountTypeDetails, getBankAccounts, getBills, getCashFlow, getExpenseAccounts, getIncomeAccounts, getInvoices, getParentAccounts, getPayments, getPaymentSources, updateAccount } from "./module/finance";
import { createExpense, getAllExpensesAccounts } from "./module/expense";
import { createExpenses } from "./module/expenses-new";
import { createBudget, getBudget, getBudgets, updateBudget, updateBudgetItemsSpent, updateBudgetStatus } from "./module/budget";

export const appRouter = router({
  createUser,
  getAllUsers,
  getAllStaffs,
  getAllStaffRole,
  createStaff,
  createStaffRole,
  getStaffById,
  getStaffByUserId,
  getAllPayrollTemplatesForOrganization,
  getAllPayrollsGroupedByMonth,
  getStaffWithPayrollTemplate,
  assignStaffToPayrollTemplate,
  updatePayrollTemplate,
  createPayrollTemplate,
  getPreviousMonthPayrolls,
  getPayrollTemplateById,
  createPayroll,
  getAllPayrollsForOrganization,
  createSinglePayroll,
  getEmployeePayrollByStaffId,
  getUserById,
  approvePayroll,
  disapprovePayroll,
  generatePayroll,
  getPayrollsByTemplateAndMonth,
  updatePayroll,
  updateStaff,
  createWorkHistory,
  getAllWorkHistory,
  getApprovedPayrollsByTemplateAndMonth,
  getUnapprovedPayrollsByTemplateAndMonth,
  createContractTemplate,
  getAllContractTemplate,
  getStaffWithContractTemplate,
  assignStaffToContractTemplate,
  getAllContractTemplatesForOrganization,
  getSingleStaffById,
  createTeam,
  getAllTeams,
  getAllParentTeams,
  createDesignation,
  getAllDesignation,
  getSingleTeamById,
  getAllTeamDesignation,
  designateStaff,
  getAllTeamMember,
  getAllStaffsWithoutRoles,
  createLeaveSetting,
  getAllLeaveSetting,
  updateLeaveSetting,
  deleteLeaveSetting,
  createLeaveApplication,
  getAllLeaveApplication,
  updateLeaveApplication,
  deleteLeaveApplication,
  getAllPendingLeaveApplicationByOrganization,
  getAllLeaveApplicationByOrganization,
  getAllApprovedLeaveApplicationByOrganization,
  getAllRejectedLeaveApplicationByOrganization,
  getLeaveApplicationById,
  changeLeaveApplicationStatus,
  createLoanSetting,
  updateLoanSetting,
  deleteLoanSetting,
  getLoanSettingById,
  getAllLoanSettingByOrganizationSlug,
  applyForLoan,
  updateLoanApplication,
  getAllLoanApplicationByUserId,
  getAllLoanApplicationByOrganizationSlug,
  changeLoanApplicationStatus,
  deleteLoanApplication,
  getLoanSettingByOrganizationSlug,
  getAllPendingLoanApplicationByOrganizationSlug,
  getAllApprovedLoanApplicationByOrganizationSlug,
  getAllRejectedLoanApplicationByOrganizationSlug,
  getLoanApplicationById,
  getAllEventOfAnOrganization,
  getAllEventsForOrganizationBySlug,
  getEventsByDateRange,
  createEvent,
  updateEvent,
  deleteEvent,
  getEvents,
  getAllEventsGroupedByMonth,
  getAllBirthdayEventsForOrganizationBySlug,
  getAllEventsForCalenderByOrgSlug,
  getTeamsByOrganizationId,
  getStaffsByOrganizationId,
  getAllNotificationByUserId,
  getNotificationById,
  deleteNotification,
  markNotificationAsRead,
  getUnreadMessageCount,
  getDraftCount,
  getUserChats,
  markMessagesAsRead,
  getActiveUsers,
  createChat,
  getChatMessages,
  sendMessage,
  getDraftMessages,
  getRecipients,
  getDraftChatById,
  updateDraft,
  sendDraft,
  getGroupChats,
  getGroupChatMessages,
  getSentMessages,
  getTrashedMessages,
  getFeedbackChats,
  createFeedback,
  getComplaintChats,
  getParentComplaintAndFeedbackMessages,
  markComplaintAsClosed,
  createComplaint,
  createBroadcast,
  saveBroadcastDraft,
  markFeedbackAsResolved,
  createPerformanceReviewTemplate,
  getAllPerformanceReviewTemplateByOrganizationSlug,
  updatePerformanceReviewTemplate,
  deletePerformanceReviewTemplate,
  deletePerformanceReview,
  updatePerformanceReview,
  assignPerformanceReviewTemplateToTeam,
  getAllPerformanceReviewByOrganizationSlug,
  getAllAssignedPerformanceReviewTemplateToTeam,
  getPerformanceReviewAssignedById,
  createPerformanceForStaffReview,
  findPerformanceReviewByStaffId,
  getUniqueTeamsFromTeamDesignationsByOrganizationId,
  getTeamDesignationsByTeamId,
  createLoanRepayment,
  disburseLoan,
  getAllLoanRepayment,
  getGroupedLoanRepayments,
  getPayrollsGroupedByMonthForStaff,
  getUserPayrollByTemplateAndMonth,
  createStaffBulkUpload,
  createOrganization,
  getAllOrganization,
  createAdmin,
  getAllAdmins,
  generateUserToken,
  verifyToken,
  getPolicyAndProcedureById,
  approvePolicyAndProcedure,
  updatePolicyAndProcedure,
  getAllPolicyAndProcedureByOrganization,
  createPolicyAndProcedure,
  deletePolicyAndProcedure,
  createExternalStaffBulkUpload,
  findPerformanceReviewById,
  getLeaveSettingByOrganizationId,
  getAllTeamDesignationsByOrganizationId,
  updateStaffDepartment,
  getSingleUserById,
  updateContractTemplate,
  deleteContractTemplate,
  updateTeamDesignation,
  getContractTemplateVersion,
  makeStaffHead,
  getUnreadNotificationCount,
  makeStaffHeadOfDepartment,
  getAllUnassignedPerformanceReviewByOrganizationSlug,
  getAllStaffForReviewByOrgIdAndRange,
  getPerformanceReviewTemplateAssignmentId,
  getAllUnassignedPerformanceReviewByOrganizationSlugAndRoleLevel,
  getPerformanceReviewRoleLevelRangeById,
  getPerformanceReviewRoleLevelAndId,
  getAllParentTeamByOrganizations,
  getAllUnassignedPerformanceReviewByOrganizationSlugAndRoleLevelOnly,
  getAllTeamPerformanceReviewsByOrg,
  updateDesignation,
  getUserRoles,
  getRoles,
  updateUserRole,
  attendToLoanManagement,
  editBankTable,
  getAllBanks,
  createBank,
  getAllBanksByOrganizationId,
  approveMultiplePayrolls,
  disapproveMultiplePayrolls,
  updateTeam,
  getAllParentTeamByOrganizationId,
  getStaffProfileByUserId,
  attendToLeaveApplication,
  getUsersByOrganizationId,
  getStaffByOrganizationId,
  getActiveOrganization,
  documentsPreference,
  homeLinkPreference,
  findDocumentPreferenceByOrganizationSlug,
  findHomeLinkPreferenceByOrganizationSlug,
  organizationLogoPreference,
  findOrganizationLogoPreferenceByOrganizationSlug,
  getAllTasksByOrganization,
  getTaskById,
  createTask,
  staffGetTaskById,
  getUsersForTaskByOrganizationId,
  staffSubmitTask,
  getStaffTaskById,
  getStaffTasksByUser,
  getAllIncomeAccounts,
  downloadAccountStatement,
  getParentAccounts,
  createAccount,
  getAccountTypeDetails,
  getAllExpensesAccounts,
  getInvoices,
  getBills,
  updateAccount,
  getBankAccounts,
  getPaymentSources,
  createPayment,
  createIncome,
  createExpense,
  createExpenses,
  getBudgets,
  updateBudgetStatus,
  getExpenseAccounts,
  updateBudget,
  createBudget,
  updateBudgetItemsSpent,
  getCashFlow,
  getPayments,
  getBudget,
  getOrganizationPreference,
  createBill,
  getIncomeAccounts,
  createInvoice,

  healthCheck: publicProcedure.query(() => {
    return { message: "API up and running..." };
  }),
});

export type AppRouter = typeof appRouter;
